name: Cache Nuget
description: ""

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        save-always: 'true'
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}