name: cd.yml
on:
  push:
    branches:
      - publish-ci

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install .NET MAUI
        run: dotnet workload install maui
      - name: Release Build
        run: dotnet build CoursePlanner/CoursePlanner.csproj -c Release -f net8.0-android -o ${{vars.OUTPUT_FOLDER}}
  cd:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{vars.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{vars.SERVICE_ACCOUNT}}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: ${{vars.APPLICATION_ID}}
          releaseFiles: ${{vars.RELEASE_FILES}}
          track: internal
          status: draft
          inAppUpdatePriority: 2