name: cd.yml
on:
  push:
    branches:
      - publish-ci

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/650797680895/locations/global/workloadIdentityPools/example-pool
          service_account: test-storage-sa@courseplanner-437101.iam.gserviceaccount.com