name: cd.yml
on:
  push:
    branches:
      - publish-ci
jobs:
  cd:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from build job
        run: |
          gh run download --name app-artifact --dir output
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{vars.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{vars.SERVICE_ACCOUNT}}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: ${{vars.APPLICATION_ID}}
          releaseFiles: ${{vars.RELEASE_FILES}}
          track: internal
          status: draft
          inAppUpdatePriority: 2