name: cd.yml
on:
  push:
    branches:
      - publish-ci

jobs:
  build:
    uses: ./.github/workflows/publish.yml



  cd:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{vars.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{vars.SERVICE_ACCOUNT}}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: ${{vars.APPLICATION_ID}}
          releaseFiles: ${{vars.RELEASE_FILES}}
          track: internal
          status: draft
          inAppUpdatePriority: 2