name: cd.yml
on:
  push:
    branches:
      - publish-ci

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.PROJECT_ID }}
          create_credentials_file: true
          workload_identity_provider: projects/courseplanner-437101/locations/global/workloadIdentityPools/github-actions-pool2/providers/github-actions-pool2