name: cd.yml
on:
  push:
    branches:
      - publish-ci
jobs:
  cd:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
      KEY_URI: ${{ secrets.KEY_URI }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      #      - name: Install .NET MAUI
      #        run: dotnet workload install maui-android

      - name: Release Build
        run: |
          ls
          dotnet run -v n --project Scripts/Scripts.csproj -- example_command


#      - id: auth
#        uses: google-github-actions/auth@v2
#        with:
#          workload_identity_provider: ${{vars.WORKLOAD_IDENTITY_PROVIDER}}
#          service_account: ${{vars.SERVICE_ACCOUNT}}
#      - uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
#          packageName: ${{vars.APPLICATION_ID}}
#          releaseFiles: ${{vars.RELEASE_FILES}}
#          track: internal
#          status: draft
#          inAppUpdatePriority: 2