name: cd.yml
on:
  push:
    branches:
      - publish-ci

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: 'Run: CD'
        run: |
          echo ${{ env.PROJECT_ID }}
          echo "hello world"

#    steps:
#      - uses: actions/checkout@v4
#      - id: 'auth'
#        name: 'Authenticate to Google Cloud'
#        uses: 'google-github-actions/auth@v2'
#        with:
#          project_id: ${{ env.PROJECT_ID }}
#          create_credentials_file: true
#          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
#          service_account: '${{env.SERVICE_ACCOUNT_EMAIL}}'