#file: noinspection UndefinedAction,UndefinedParamsPresent

on:
  workflow_dispatch:
  pull_request:
    branches:
      - current

jobs:
  build_test:
    name: Build And Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./actions/setup-dotnet-maui
      - name: Cache Nuget
        uses: ./actions/cache-nuget
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
#      - name: Test
#        uses: ./actions/testing
#        with:
#          configuration: Debug