#file: noinspection UndefinedAction,UndefinedParamsPresent

on:
  workflow_dispatch:
  pull_request:
    branches:
      - current

env:
  DOTNET_VERSION: 8.0

jobs:
  build_test:
    name: Build And Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./actions/setup-dotnet-maui
      - name: Cache Nuget
        uses: ./actions/cache-nuget
      - name: Cache Dotnet
        uses: actions/cache@v4
        with:
          path: /usr/share/dotnet
          key: ${{runner.os}}-${{env.DOTNET_VERSION}}

#      - name: Test
#        uses: ./actions/testing
#        with:
#          configuration: Debug