on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
      - current

jobs:
  build_test:
    name: Build And Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ""
        uses: ./actions/ci-action


