#file: noinspection UndefinedAction
on:
  workflow_dispatch: 
  pull_request:
    branches:
      - main

jobs:
  build_test:
    name: Build And Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Full Setup
        uses: ./actions/full-setup-dotnet-maui
      - name: Cache Nuget
        uses: ./actions/cache-nuget
      - name: Release Build
        run: dotnet build CoursePlanner/CoursePlanner.csproj -c Release -f net8.0-android
      - name: Test
        uses: ./actions/testing