on:
  push:
    branches:
      - publish-ci

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install .NET MAUI
        run: dotnet workload install maui

      - name: Write Keystore File
        run: |  
          function ConvertFrom-Base64{
            param(
            [string]$base64
            )
            return [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($base64))
          }
          $res = ConvertFrom-Base64 ${{ secrets.COURSEPLANNER_KEYSTORE_CONTENTS_BASE64 }}
          $res > ${{ runner.workspace }}/.keystore

      - name: Generate APK
        env:
          COURSEPLANNER_ANDROID_SIGNING_KEY_STORE: ${{ secrets.COURSEPLANNER_ANDROID_SIGNING_KEY_STORE }}
          COURSEPLANNER_ANDROID_SIGNING_KEY_ALIAS: ${{ secrets.COURSEPLANNER_ANDROID_SIGNING_KEY_ALIAS }}
          COURSEPLANNER_KEY: ${{ secrets.COURSEPLANNER_KEY }}
        run: dotnet publish CoursePlanner/CoursePlanner.csproj -f net8.0-android -c Release `
          -p:AndroidKeyStore=true `
          -p:AndroidSigningKeyStore=${{ runner.workspace }}/.keystore`
          -p:AndroidSigningKeyAlias=$env:COURSEPLANNER_ANDROID_SIGNING_KEY_ALIAS `
          -p:AndroidSigningKeyPass=$env:COURSEPLANNER_KEY `
          -p:AndroidSigningStorePass=$env:COURSEPLANNER_KEY

      - name: Publish Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.tbui17.courseplanner
          releaseFiles: CoursePlanner/bin/Release/net8.0-android/publish/com.tbui17.courseplanner-Signed.aab
          track: internal
          status: completed